"""
TALK: TRANSMISSION OCCURRING, BLUE
CONNECT: GREEN, ACTIVELY ON AND CONNECTED
RESET: WHITE, LOCAL HOST ACTIVE

"""



RESET = 21  # PHYSICAL PIN 27 ON PICO W
CONNECT = 20  # PHYSICAL PIN 26 ON PICO W
DISCONNECT = 19  # PHYSICAL PIN 25 ON PICO W
TALK = 18  # PHYSICAL PIN 24 ON PICO W
isBlinkable = True




SDA1 = 14  # PHYS 19 GPIO 14
SCL1 = 15  # PHYS 20 GPIO 15



RFReceiver = 12  # PHYSICAL PIN 16 ON PICO W
FLAMMABLE_GAS_SENSOR = 26  # PHYSICAL PIN 31 ON PICO W
TEMPERATURE_SENSOR_SCL = SCL1  # PHYSICAL PIN 2 ON PICO W
TEMPERATURE_SENSOR_SDA = SDA1  # PHYSICAL PIN 1 ON PICO W
PROXIMITY_SENSOR = 6  # PHYSICAL PIN 9 ON PICO W
HIGH = 1  # Constant Def


LED_PINS = [TALK, CONNECT, RESET, DISCONNECT]

